name: fisheye

channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - matplotlib>=3.1.1
  - scipy>=1.0.0
  - pysam
  - viennarna
  - bowtie2
  - pip:
      - pathos
      - fire
      - pyfaidx
      - primer3-py
      - editdistance

